/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SpotsRouteImport } from './routes/spots'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as GroupsSlugRouteImport } from './routes/groups.$slug'
import { Route as GroupsNewRouteImport } from './routes/groups.new'
import { Route as SpotsIndexRouteImport } from './routes/spots.index'
import { Route as SpotsSlugRouteImport } from './routes/spots.$slug'
import { Route as SpotsNewRouteImport } from './routes/spots.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotsRoute = SpotsRouteImport.update({
  id: '/spots',
  path: '/spots',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EventsRoute,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsRoute,
} as any)
const GroupsSlugRoute = GroupsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GroupsRoute,
} as any)
const GroupsNewRoute = GroupsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => GroupsRoute,
} as any)
const SpotsIndexRoute = SpotsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpotsRoute,
} as any)
const SpotsSlugRoute = SpotsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SpotsRoute,
} as any)
const SpotsNewRoute = SpotsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SpotsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/groups': typeof GroupsRouteWithChildren
  '/login': typeof LoginRoute
  '/office': typeof OfficeRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/spots': typeof SpotsRouteWithChildren
  '/events/new': typeof EventsNewRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/groups/new': typeof GroupsNewRoute
  '/spots/$slug': typeof SpotsSlugRoute
  '/spots/new': typeof SpotsNewRoute
  '/events/': typeof EventsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/spots/': typeof SpotsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/office': typeof OfficeRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/events/new': typeof EventsNewRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/groups/new': typeof GroupsNewRoute
  '/spots/$slug': typeof SpotsSlugRoute
  '/spots/new': typeof SpotsNewRoute
  '/events': typeof EventsIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/spots': typeof SpotsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/groups': typeof GroupsRouteWithChildren
  '/login': typeof LoginRoute
  '/office': typeof OfficeRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/spots': typeof SpotsRouteWithChildren
  '/events/new': typeof EventsNewRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/groups/new': typeof GroupsNewRoute
  '/spots/$slug': typeof SpotsSlugRoute
  '/spots/new': typeof SpotsNewRoute
  '/events/': typeof EventsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/spots/': typeof SpotsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/favorites'
    | '/groups'
    | '/login'
    | '/office'
    | '/profile'
    | '/settings'
    | '/spots'
    | '/events/new'
    | '/groups/$slug'
    | '/groups/new'
    | '/spots/$slug'
    | '/spots/new'
    | '/events/'
    | '/groups/'
    | '/spots/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/login'
    | '/office'
    | '/profile'
    | '/settings'
    | '/events/new'
    | '/groups/$slug'
    | '/groups/new'
    | '/spots/$slug'
    | '/spots/new'
    | '/events'
    | '/groups'
    | '/spots'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/favorites'
    | '/groups'
    | '/login'
    | '/office'
    | '/profile'
    | '/settings'
    | '/spots'
    | '/events/new'
    | '/groups/$slug'
    | '/groups/new'
    | '/spots/$slug'
    | '/spots/new'
    | '/events/'
    | '/groups/'
    | '/spots/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  GroupsRoute: typeof GroupsRouteWithChildren
  LoginRoute: typeof LoginRoute
  OfficeRoute: typeof OfficeRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SpotsRoute: typeof SpotsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spots': {
      id: '/spots'
      path: '/spots'
      fullPath: '/spots'
      preLoaderRoute: typeof SpotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/new': {
      id: '/events/new'
      path: '/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof EventsRoute
    }
    '/groups/': {
      id: '/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/groups/$slug': {
      id: '/groups/$slug'
      path: '/$slug'
      fullPath: '/groups/$slug'
      preLoaderRoute: typeof GroupsSlugRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/groups/new': {
      id: '/groups/new'
      path: '/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof GroupsNewRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/spots/': {
      id: '/spots/'
      path: '/'
      fullPath: '/spots/'
      preLoaderRoute: typeof SpotsIndexRouteImport
      parentRoute: typeof SpotsRoute
    }
    '/spots/$slug': {
      id: '/spots/$slug'
      path: '/$slug'
      fullPath: '/spots/$slug'
      preLoaderRoute: typeof SpotsSlugRouteImport
      parentRoute: typeof SpotsRoute
    }
    '/spots/new': {
      id: '/spots/new'
      path: '/new'
      fullPath: '/spots/new'
      preLoaderRoute: typeof SpotsNewRouteImport
      parentRoute: typeof SpotsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsRouteChildren {
  EventsNewRoute: typeof EventsNewRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsNewRoute: EventsNewRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface GroupsRouteChildren {
  GroupsSlugRoute: typeof GroupsSlugRoute
  GroupsNewRoute: typeof GroupsNewRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
}

const GroupsRouteChildren: GroupsRouteChildren = {
  GroupsSlugRoute: GroupsSlugRoute,
  GroupsNewRoute: GroupsNewRoute,
  GroupsIndexRoute: GroupsIndexRoute,
}

const GroupsRouteWithChildren =
  GroupsRoute._addFileChildren(GroupsRouteChildren)

interface SpotsRouteChildren {
  SpotsSlugRoute: typeof SpotsSlugRoute
  SpotsNewRoute: typeof SpotsNewRoute
  SpotsIndexRoute: typeof SpotsIndexRoute
}

const SpotsRouteChildren: SpotsRouteChildren = {
  SpotsSlugRoute: SpotsSlugRoute,
  SpotsNewRoute: SpotsNewRoute,
  SpotsIndexRoute: SpotsIndexRoute,
}

const SpotsRouteWithChildren = SpotsRoute._addFileChildren(SpotsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  GroupsRoute: GroupsRouteWithChildren,
  LoginRoute: LoginRoute,
  OfficeRoute: OfficeRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SpotsRoute: SpotsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
